version: "3.7"
services:
  autorok:
    image: "300481/autorok:0.1.1"
    restart: always
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    environment:
    - AUTOROK_CONFIG_URL
    - S6_KEEP_ENV=1